services:
  streamlit_gear_app:
    build: .
    container_name: streamlit_turbofan_app
    ports:
      - "8501:8501"
    environment:
     - OS_TYPE=linux
    volumes:
     - .:/app
    restart: always